######### Configure these for each git tag release #########
git_tag:
  - "cuda-core-v0.3.1"
bindings_version:
  - "12.9.0"
core_version:
  - "0.3.1"
build_bindings:
  - False
build_core:
  - True
############################################################

# Produce two builds:
# 1. CUDA >=12.0,<12.2 and depends on cuda-nvcc-impl
# 2. CUDA >=12.2,<13.0 and depends on cuda-nvvm
build_use_nvvm:
  - False
  - True
