######### Configure these for each git tag release #########
git_tag:
  - "v12.8.0"
bindings_version:
  - "12.8.0"
core_version:
  - "0.1.1"
build_bindings:
  - True
build_core:
  - False
############################################################
