######### Configure these for each git tag release #########
git_tag:
  - "cuda-core-v0.1.1"
bindings_version:
  - "12.6.2"
core_version:
  - "0.1.1"
build_bindings:
  - False
build_core:
  - True
############################################################
