######### Configure these for each git tag release #########
git_tag:
  - "v12.9.1"
bindings_version:
  - "12.9.1"
core_version:
  - "0.3.1"
build_bindings:
  - True
build_core:
  - False
############################################################
