arm_variant_type:  # [aarch64]
  - sbsa           # [aarch64]
c_compiler_version:
  - 10
cxx_compiler_version:
  - 10
cuda_compiler_version:
  - 12.0
cuda_compiler:
  - cuda-nvcc
fortran_compiler_version:
  - 10
cudnn:
  - 8
cdt_name:
  - cos7
docker_image:
  - quay.io/condaforge/linux-anvil-cos7-x86_64  # [linux and x86_64]
  - quay.io/condaforge/linux-anvil-aarch64      # [linux and aarch64]
  - quay.io/condaforge/linux-anvil-ppc64le      # [linux and ppc64le]
