# Starting CUDA Python 11.7.1, CUDA headers are required to build the project, so we
# must use the CUDA containers that offer the needed headers

arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]

docker_image:                                           # [os.environ.get("BUILD_PLATFORM", "").startswith("linux")]
   - quay.io/condaforge/linux-anvil-cuda:11.7           # [linux64 and os.environ.get("BUILD_PLATFORM") == "linux-64"]
   - quay.io/condaforge/linux-anvil-ppc64le-cuda:11.7   # [ppc64le and os.environ.get("BUILD_PLATFORM") == "linux-ppc64le"]
   - quay.io/condaforge/linux-anvil-aarch64-cuda:11.7   # [aarch64 and os.environ.get("BUILD_PLATFORM") == "linux-aarch64"]

c_compiler_version:        # [linux]
  - 10                     # [linux64]
  - 10                     # [ppc64le]
  - 10                     # [aarch64]
cxx_compiler_version:      # [linux]
  - 10                     # [linux64]
  - 10                     # [ppc64le]
  - 10                     # [aarch64]
fortran_compiler_version:  # [linux]
  - 10                     # [linux64]
  - 10                     # [ppc64le]
  - 10                     # [aarch64]

cuda_compiler:
  - nvcc

cuda_compiler_version:
  - 11.7                   # [linux64]
  - 11.7                   # [ppc64le]
  - 11.7                   # [aarch64]
  - 11.7                   # [win64]

cudnn:
  - 8                      # [linux64]
  - 8                      # [ppc64le]
  - 8                      # [aarch64]
  - 8                      # [win64]

cdt_name:  # [linux]
  - cos7   # [linux64]
  - cos7   # [ppc64le]
  - cos7   # [aarch64]
