{% set name = "cuda-python" %}
{% set version = "12.1.0" %}
{% set major_version = version.split(".")[0] %}
{% set minor_version = version.split(".")[1] %}
{% set patch_version = version.split(".")[2] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cuda-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f89f7de4d48b6ecb4792412317131c40c73d8b8710f89eb4eaaeff2f1dc13261

build:
  number: 0
  skip: true  # [py<37 or osx or cuda_compiler_version != "12.1"]
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
  # TODO: Do we need run_exports in CUDA 12? I think so?
  run_exports:
    - cuda-python >=12.1.0
  # TODO: Do we need to ignore anything in CUDA 12?
  #ignore_run_exports:
  #  - cuda-cudart
  #  - cuda-nvrtc

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - setuptools
    - cython
    - python
    - pyclibrary
    - pip
  run:
    - python
    - cuda-version >=12.1
    - cuda-cudart
    - cuda-nvrtc
    - pywin32  # [win]
  run_constrained:
    - __glibc >=2.17  # [linux]

test:
  imports:
    - cuda
    - cuda.cuda
    - cuda.cudart

about:
  home: https://github.com/NVIDIA/cuda-python
  license: LicenseRef-NVIDIA-SOFTWARE-LICENSE
  license_file: LICENSE
  license_url: https://github.com/NVIDIA/cuda-python/blob/main/LICENSE
  summary: CUDA Python Low-level Bindings
  description: |
    CUDA Python provides a standard set of low-level interfaces,
    providing full coverage of and access to the CUDA host APIs from Python.
  doc_url: https://nvidia.github.io/cuda-python/
  dev_url: https://github.com/NVIDIA/cuda-python

extra:
  recipe-maintainers:
    - m3vaz
    - jakirkham
    - mmccarty
    - leofang
